"""High-level orchestration for project/batch planning and placeholder materialization."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List

from app.models import Batch, Project, VersionSpec
from app.project_storage import ProjectRepository
from app.tidy_dataset import TidyDatasetWriter
from app.version_resolver import resolve_versions


@dataclass(frozen=True)
class PlanningSummary:
    project_id: str
    batch_id: str
    version_count: int
    version_ids: List[str]
    project_root: str
    dataset_files: Dict[str, Any]
    table_file: str


def materialize_batch_plan(
    project: Project,
    batch: Batch,
    *,
    projects_root: str | Path = "projects",
    library_root: str | Path | None = None,
    cfg_placeholder_text: str = "; generated by WUT Batcher planner\n",
) -> PlanningSummary:
    if not batch.project_id:
        batch.project_id = project.project_id
    if batch.project_id != project.project_id:
        raise ValueError(f"Batch project_id mismatch: {batch.project_id} != {project.project_id}")

    repo = ProjectRepository(projects_root=projects_root)
    paths = repo.init_project(project)
    repo.save_batch(project.project_id, batch)

    existing_ids = repo.existing_version_ids(project.project_id)
    resolved = resolve_versions(
        project.constraints,
        batch,
        existing_version_ids=existing_ids,
        strict=True,
    )
    versions: List[VersionSpec] = resolved.versions

    materialized = repo.materialize_versions(
        project.project_id,
        batch.batch_id,
        versions,
        cfg_placeholder_text=cfg_placeholder_text,
    )

    writer = TidyDatasetWriter(paths.project_dir, library_root=library_root)
    version_dataset = writer.write_plan_bundle(project=project, batch=batch, versions=materialized)
    table_result = writer.write_project_table(project_id=project.project_id)

    return PlanningSummary(
        project_id=project.project_id,
        batch_id=batch.batch_id,
        version_count=len(materialized),
        version_ids=[version.version_id for version in materialized],
        project_root=str(paths.project_dir),
        dataset_files={
            "versions": version_dataset,
            "schema": str(writer.schema_path),
            "project_db": str(writer.project_db_path),
            "global_db": str(writer.global_db_path),
        },
        table_file=str(table_result["csv_path"]),
    )
