"""High-level orchestration for project/batch planning and placeholder materialization."""

from __future__ import annotations

from dataclasses import dataclass
import math
from pathlib import Path
import re
from typing import Any, Dict, List

from app.models import Batch, Project, VersionSpec
from app.project_storage import ProjectRepository
from app.tidy_dataset import TidyDatasetWriter
from app.version_resolver import resolve_versions


@dataclass(frozen=True)
class PlanningSummary:
    project_id: str
    batch_id: str
    version_count: int
    version_ids: List[str]
    project_root: str
    dataset_files: Dict[str, Any]
    table_file: str


_NUMERIC_TEXT_RE = re.compile(r"^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$")


def _canonical_plan_value(value: Any) -> Any:
    """Normalize serialization-only numeric differences in immutable plans."""
    if isinstance(value, dict):
        return {key: _canonical_plan_value(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_canonical_plan_value(item) for item in value]
    if isinstance(value, str):
        token = value.strip()
        if _NUMERIC_TEXT_RE.fullmatch(token):
            try:
                numeric = float(token)
            except ValueError:
                return value
            if math.isfinite(numeric):
                return numeric
    return value


def _version_plan_signature(version: VersionSpec) -> Dict[str, Any]:
    """Return the immutable plan portion of a materialized version."""

    return {
        "project_id": str(version.project_id),
        "batch_id": str(version.batch_id),
        "sweep_mode": str(version.sweep_mode),
        "sequence_index": int(version.sequence_index),
        "parameters": _canonical_plan_value(dict(version.parameters)),
        "variable_parameters": _canonical_plan_value(dict(version.variable_parameters)),
        "unset_parameters": sorted(str(item) for item in version.unset_parameters),
        "sweep_parameters": _canonical_plan_value(dict(version.sweep_parameters)),
        "sim_export_settings": _canonical_plan_value(dict(version.sim_export_settings)),
        "geometry_id": str(version.geometry_id),
        "driver_snapshot_hash": str(version.driver_snapshot.get("snapshot_hash") or ""),
    }


def match_materialized_versions(
    existing_versions: List[VersionSpec],
    desired_versions: List[VersionSpec],
) -> List[VersionSpec]:
    """Match one canonical stored version to every desired plan row.

    Older releases could create the same version cohort again on every run.
    Selecting the lowest-ID match for each desired row keeps those projects
    runnable without creating a third cohort.  Extra historical duplicates are
    intentionally left untouched for a separate, evidence-backed cleanup.
    """

    remaining = sorted(existing_versions, key=lambda item: str(item.version_id))
    matched: List[VersionSpec] = []
    for desired in sorted(desired_versions, key=lambda item: (int(item.sequence_index), str(item.version_id))):
        desired_signature = _version_plan_signature(desired)
        match_index = next(
            (
                index
                for index, candidate in enumerate(remaining)
                if _version_plan_signature(candidate) == desired_signature
            ),
            None,
        )
        if match_index is None:
            return []
        matched.append(remaining.pop(match_index))
    return matched


def materialize_batch_plan(
    project: Project,
    batch: Batch,
    *,
    projects_root: str | Path = "projects",
    library_root: str | Path | None = None,
    cfg_placeholder_text: str = "; generated by WUT Batcher planner\n",
) -> PlanningSummary:
    if not batch.project_id:
        batch.project_id = project.project_id
    if batch.project_id != project.project_id:
        raise ValueError(f"Batch project_id mismatch: {batch.project_id} != {project.project_id}")

    repo = ProjectRepository(projects_root=projects_root)
    paths = repo.init_project(project)
    existing_batch_versions = repo.list_versions(project.project_id, batch_id=batch.batch_id)
    reuse_existing = bool(existing_batch_versions)
    if existing_batch_versions:
        desired = resolve_versions(
            project.constraints,
            batch,
            existing_version_ids=(),
            strict=True,
        )
        versions = match_materialized_versions(existing_batch_versions, desired.versions)
        if len(versions) != len(desired.versions):
            raise ValueError(
                f"Batch {batch.batch_id} is already materialized with a different version plan; "
                "create a new batch instead of changing an existing batch definition."
            )
    else:
        existing_ids = repo.existing_version_ids(project.project_id)
        resolved = resolve_versions(
            project.constraints,
            batch,
            existing_version_ids=existing_ids,
            strict=True,
        )
        versions = resolved.versions

    repo.save_batch(project.project_id, batch)

    if reuse_existing:
        # Do not rewrite version.json here: completed versions contain run and
        # stage diagnostics beyond VersionSpec's immutable planning fields.
        materialized = versions
    else:
        materialized = repo.materialize_versions(
            project.project_id,
            batch.batch_id,
            versions,
            cfg_placeholder_text=cfg_placeholder_text,
        )

    writer = TidyDatasetWriter(paths.project_dir, library_root=library_root)
    version_dataset = writer.write_plan_bundle(project=project, batch=batch, versions=materialized)
    table_result = writer.write_project_table(project_id=project.project_id)

    return PlanningSummary(
        project_id=project.project_id,
        batch_id=batch.batch_id,
        version_count=len(materialized),
        version_ids=[version.version_id for version in materialized],
        project_root=str(paths.project_dir),
        dataset_files={
            "versions": version_dataset,
            "schema": str(writer.schema_path),
            "project_db": str(writer.project_db_path),
            "global_db": str(writer.global_db_path),
        },
        table_file=str(table_result["csv_path"]),
    )
