"""Runtime orchestration for staged ATH -> AKABAK -> VACS execution."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import time
from typing import Any, Dict, List, Optional, Sequence

from app.batch_orchestrator import materialize_batch_plan
from app.cfg_renderer import render_cfg_text
from app.models import Batch, Project
from app.safe_cleanup import guarded_delete_tree
from app.runners import AkabakRunner, AthRunner, RunnerResult, VacsRunner, parse_ath_dimensions
from app.tidy_dataset import TidyDatasetWriter


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _read_json(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object in {path}")
    return payload


@dataclass(frozen=True)
class StageExecution:
    version_id: str
    stage: str
    status: str
    exit_code: int
    timed_out: bool
    summary_log: str


@dataclass(frozen=True)
class RuntimeSummary:
    project_id: str
    batch_id: str
    project_root: str
    versions: List[str]
    stage_results: List[StageExecution]
    ath_dimension_rows: int
    cleanup_results: List[Dict[str, Any]]


def _version_json_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "version.json"


def _version_cfg_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "cfg" / "input.cfg"


def _version_abec_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "abec" / "Project.abec"


def _version_ath_work_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "ath_work"


def _version_logs_dir(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "logs"


def _load_template_text(template_cfg_path: Optional[str | Path]) -> str:
    if template_cfg_path is None:
        return "; autogenerated cfg template\n"
    return Path(template_cfg_path).read_text(encoding="utf-8")


def _update_version_state(project_root: Path, version_id: str, updates: Dict[str, Any]) -> None:
    path = _version_json_path(project_root, version_id)
    payload = _read_json(path)
    payload.update(updates)
    _write_json(path, payload)


def _stage_from_result(version_id: str, stage: str, result: RunnerResult) -> StageExecution:
    return StageExecution(
        version_id=version_id,
        stage=stage,
        status="ok" if result.ok else "failed",
        exit_code=result.exit_code,
        timed_out=result.timed_out,
        summary_log=result.summary_log,
    )


def run_batch_pipeline(
    project: Project,
    batch: Batch,
    *,
    projects_root: str | Path = "projects",
    template_cfg_path: str | Path | None = None,
    ath_executable: str | Path | None = None,
    akabak_executable: str | Path | None = None,
    vacs_executable: str | Path | None = None,
    ath_base_args: Sequence[str] | None = None,
    akabak_base_args: Sequence[str] | None = None,
    vacs_base_args: Sequence[str] | None = None,
    continue_on_error: bool = True,
) -> RuntimeSummary:
    planning_summary = materialize_batch_plan(
        project=project,
        batch=batch,
        projects_root=projects_root,
    )
    project_root = Path(planning_summary.project_root)
    template_text = _load_template_text(template_cfg_path)
    writer = TidyDatasetWriter(project_root)

    ath_runner = AthRunner(ath_executable, base_args=ath_base_args) if ath_executable else None
    akabak_runner = AkabakRunner(akabak_executable, base_args=akabak_base_args) if akabak_executable else None
    vacs_runner = VacsRunner(vacs_executable, base_args=vacs_base_args) if vacs_executable else None

    stage_results: List[StageExecution] = []
    ath_dimension_rows = 0
    cleanup_results: List[Dict[str, Any]] = []
    versions_root = project_root / "versions"

    for version_id in planning_summary.version_ids:
        version_started = time.perf_counter()
        version_payload = _read_json(_version_json_path(project_root, version_id))
        version_params = dict(version_payload.get("parameters", {}) or {})
        runner_mode = str(batch.runner_mode or project.constraints.runner_mode)
        ath_stage_ok = ath_runner is None
        akabak_stage_ok = akabak_runner is None
        vacs_stage_ok = vacs_runner is None

        cfg_path = _version_cfg_path(project_root, version_id)
        cfg_text = render_cfg_text(
            template_text=template_text,
            parameters=version_params,
            version_id=version_id,
            runner_mode=runner_mode,
        )
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        cfg_path.write_text(cfg_text, encoding="utf-8")

        if ath_runner:
            ath_work_dir = _version_ath_work_path(project_root, version_id)
            ath_work_dir.mkdir(parents=True, exist_ok=True)
            ath_result = ath_runner.run_cfg(
                cfg_path,
                version_logs_dir=_version_logs_dir(project_root, version_id),
                workdir=ath_work_dir,
            )
            stage_results.append(_stage_from_result(version_id, "ath", ath_result))
            _update_version_state(
                project_root,
                version_id,
                {
                    "status": "ath_ok" if ath_result.ok else "ath_failed",
                    "ath_result": {
                        "exit_code": ath_result.exit_code,
                        "timed_out": ath_result.timed_out,
                        "stdout_log": ath_result.stdout_log,
                        "stderr_log": ath_result.stderr_log,
                        "summary_log": ath_result.summary_log,
                    },
                },
            )
            writer.update_version_status(version_id, status="ath_ok" if ath_result.ok else "ath_failed")
            ath_stage_ok = ath_result.ok

            ath_stdout = Path(ath_result.stdout_log).read_text(encoding="utf-8")
            dims = parse_ath_dimensions(ath_stdout)
            if dims.raw_line:
                writer.write_ath_dimensions(
                    [
                        {
                            "project_id": project.project_id,
                            "batch_id": batch.batch_id,
                            "version_id": version_id,
                            "horn_length_mm": dims.horn_length_mm,
                            "horn_width_mm": dims.horn_width_mm,
                            "horn_height_mm": dims.horn_height_mm,
                            "raw_line": dims.raw_line,
                            "source_file": ath_result.stdout_log,
                        }
                    ]
                )
                ath_dimension_rows += 1
            if not ath_result.ok and not continue_on_error:
                elapsed = time.perf_counter() - version_started
                writer.update_version_status(
                    version_id,
                    status="failed",
                    duration_seconds=elapsed,
                    finished_at=_now_iso(),
                )
                continue

        if akabak_runner:
            akabak_result = akabak_runner.run_project(
                _version_abec_path(project_root, version_id),
                version_logs_dir=_version_logs_dir(project_root, version_id),
            )
            stage_results.append(_stage_from_result(version_id, "akabak", akabak_result))
            _update_version_state(
                project_root,
                version_id,
                {
                    "status": "akabak_ok" if akabak_result.ok else "akabak_failed",
                    "akabak_result": {
                        "exit_code": akabak_result.exit_code,
                        "timed_out": akabak_result.timed_out,
                        "summary_log": akabak_result.summary_log,
                    },
                },
            )
            writer.update_version_status(version_id, status="akabak_ok" if akabak_result.ok else "akabak_failed")
            akabak_stage_ok = akabak_result.ok
            if not akabak_result.ok and not continue_on_error:
                elapsed = time.perf_counter() - version_started
                writer.update_version_status(
                    version_id,
                    status="failed",
                    duration_seconds=elapsed,
                    finished_at=_now_iso(),
                )
                continue

        if vacs_runner:
            vacs_result = vacs_runner.run_export(
                _version_abec_path(project_root, version_id),
                version_logs_dir=_version_logs_dir(project_root, version_id),
            )
            stage_results.append(_stage_from_result(version_id, "vacs", vacs_result))
            _update_version_state(
                project_root,
                version_id,
                {
                    "status": "vacs_ok" if vacs_result.ok else "vacs_failed",
                    "vacs_result": {
                        "exit_code": vacs_result.exit_code,
                        "timed_out": vacs_result.timed_out,
                        "summary_log": vacs_result.summary_log,
                    },
                },
            )
            writer.update_version_status(version_id, status="vacs_ok" if vacs_result.ok else "vacs_failed")
            vacs_stage_ok = vacs_result.ok

        elapsed = time.perf_counter() - version_started
        final_ok = ath_stage_ok and akabak_stage_ok and vacs_stage_ok
        writer.update_version_status(
            version_id,
            status="completed" if final_ok else "failed",
            duration_seconds=elapsed,
            finished_at=_now_iso(),
        )

        if final_ok and vacs_runner is not None:
            cleanup_result = guarded_delete_tree(
                _version_ath_work_path(project_root, version_id),
                allowed_root=versions_root,
                expected_dir_name="ath_work",
                deny_paths=(project_root, project_root.parent, versions_root),
            )
            cleanup_results.append(
                {
                    "version_id": version_id,
                    "target": cleanup_result.target,
                    "deleted": cleanup_result.deleted,
                    "reason": cleanup_result.reason,
                }
            )
        elif vacs_runner is None:
            cleanup_results.append(
                {
                    "version_id": version_id,
                    "target": str(_version_ath_work_path(project_root, version_id)),
                    "deleted": False,
                    "reason": "skipped_without_vacs_stage",
                }
            )

    return RuntimeSummary(
        project_id=project.project_id,
        batch_id=batch.batch_id,
        project_root=str(project_root),
        versions=list(planning_summary.version_ids),
        stage_results=stage_results,
        ath_dimension_rows=ath_dimension_rows,
        cleanup_results=cleanup_results,
    )
