"""Runtime orchestration for staged ATH -> AKABAK -> VACS execution."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
import time
import uuid
from typing import Any, Dict, List, Optional, Sequence

from app.batch_orchestrator import materialize_batch_plan
from app.cfg_renderer import render_cfg_text
from app.export_specs import parse_export_specs
from app.models import Batch, Project
from app.safe_cleanup import guarded_delete_tree
from app.runners import AkabakRunner, AthRunner, RunnerResult, VacsRunner, parse_ath_dimensions
from app.tidy_dataset import TidyDatasetWriter
from app.vacs_export_pipeline import VacsExportPipelineError, run_vacs_export_specs
from app.vacs_txt_parser import parse_vacs_txt_file


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _read_json(path: Path) -> Dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object in {path}")
    return payload


@dataclass(frozen=True)
class StageExecution:
    version_id: str
    stage: str
    status: str
    exit_code: int
    timed_out: bool
    summary_log: str


@dataclass(frozen=True)
class RuntimeSummary:
    run_id: str
    run_status: str
    project_id: str
    batch_id: str
    project_root: str
    versions: List[str]
    stage_results: List[StageExecution]
    ath_dimension_rows: int
    cleanup_results: List[Dict[str, Any]]
    dry_run: bool = False


def _version_json_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "version.json"


def _version_cfg_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "cfg" / "input.cfg"


def _version_abec_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "abec" / "Project.abec"


def _version_ath_work_path(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "ath_work"


def _version_logs_dir(project_root: Path, version_id: str) -> Path:
    return project_root / "versions" / version_id / "logs"


def _version_exports_dir(project_root: Path, version_id: str, run_id: str) -> Path:
    return project_root / "versions" / version_id / "exports" / run_id


def _load_template_text(template_cfg_path: Optional[str | Path]) -> str:
    if template_cfg_path is None:
        return "; autogenerated cfg template\n"
    return Path(template_cfg_path).read_text(encoding="utf-8")


def _update_version_state(project_root: Path, version_id: str, updates: Dict[str, Any]) -> None:
    path = _version_json_path(project_root, version_id)
    payload = _read_json(path)
    payload.update(updates)
    _write_json(path, payload)


def _stage_from_result(version_id: str, stage: str, result: RunnerResult) -> StageExecution:
    return StageExecution(
        version_id=version_id,
        stage=stage,
        status="ok" if result.ok else "failed",
        exit_code=result.exit_code,
        timed_out=result.timed_out,
        summary_log=result.summary_log,
    )


def _ingest_vacs_exports(
    *,
    writer: TidyDatasetWriter,
    project: Project,
    batch: Batch,
    run_id: str,
    version_id: str,
    exports_dir: Path,
) -> Dict[str, Any]:
    export_files = sorted(path for path in exports_dir.rglob("*.txt") if path.is_file())
    parse_errors: List[str] = []
    rows: List[Dict[str, Any]] = []

    for path in export_files:
        try:
            parsed = parse_vacs_txt_file(path)
        except ValueError as exc:
            parse_errors.append(f"{path.name}: {exc}")
            continue

        for series in parsed.series:
            variant = "default"
            metadata = parsed.export_meta.get("metadata")
            if isinstance(metadata, dict):
                variant = str(metadata.get("variant", metadata.get("Variant", "default")))
            for point_index, point in enumerate(series.points):
                rows.append(
                    {
                        "project_id": project.project_id,
                        "batch_id": batch.batch_id,
                        "run_id": run_id,
                        "version_id": version_id,
                        "graph_type": parsed.graph_type,
                        "graph_kind": parsed.graph_type,
                        "variant": variant,
                        "x_name": parsed.x_name,
                        "y_name": parsed.y_name,
                        "x_axis": parsed.x_name,
                        "y_axis": parsed.y_name,
                        "x_unit": parsed.x_unit,
                        "y_unit": parsed.y_unit,
                        "series_kind": series.series_kind,
                        "angle_deg": series.angle_deg,
                        "series_label": series.label,
                        "series_meta": series.meta,
                        "x_value": point.x_value,
                        "y_value": point.y_value,
                        "y_imag": point.y_imag,
                        "point_index": point_index,
                        "source_file": str(path),
                        "export_meta": parsed.export_meta,
                        "meta_json": parsed.export_meta,
                    }
                )

    write_result: Dict[str, Any] = {}
    if rows:
        write_result = writer.write_measurements(rows)

    return {
        "export_dir": str(exports_dir),
        "files_found": len(export_files),
        "rows_prepared": len(rows),
        "parse_errors": parse_errors,
        "write_result": write_result,
    }


def run_batch_pipeline(
    project: Project,
    batch: Batch,
    *,
    projects_root: str | Path = "projects",
    template_cfg_path: str | Path | None = None,
    ath_executable: str | Path | None = None,
    akabak_executable: str | Path | None = None,
    vacs_executable: str | Path | None = None,
    ath_base_args: Sequence[str] | None = None,
    akabak_base_args: Sequence[str] | None = None,
    vacs_base_args: Sequence[str] | None = None,
    continue_on_error: bool = True,
    dry_run: bool = False,
    run_id: Optional[str] = None,
    git_commit: Optional[str] = None,
    app_version: Optional[str] = "0.1-rebuild",
    settings_hash: Optional[str] = None,
) -> RuntimeSummary:
    planning_summary = materialize_batch_plan(project=project, batch=batch, projects_root=projects_root)
    project_root = Path(planning_summary.project_root)
    template_text = _load_template_text(template_cfg_path)
    writer = TidyDatasetWriter(project_root)
    effective_run_id = run_id or str(uuid.uuid4())

    writer.create_run(
        run_id=effective_run_id,
        project_id=project.project_id,
        batch_id=batch.batch_id,
        status="running",
        git_commit=git_commit,
        app_version=app_version,
        settings_hash=settings_hash,
    )
    writer.write_run_versions(
        [
            {
                "run_id": effective_run_id,
                "version_id": version_id,
                "project_id": project.project_id,
                "batch_id": batch.batch_id,
                "status": "planned",
            }
            for version_id in planning_summary.version_ids
        ]
    )

    sim_export_payload = batch.sim_export_settings.to_dict()
    export_specs = parse_export_specs(sim_export_payload)
    vacs_required = bool(export_specs)
    vacs_version = str(sim_export_payload.get("vacs_version", "default") or "default")

    ath_runner = None if dry_run or not ath_executable else AthRunner(ath_executable, base_args=ath_base_args)
    akabak_runner = None if dry_run or not akabak_executable else AkabakRunner(akabak_executable, base_args=akabak_base_args)
    vacs_runner = None if dry_run or not vacs_executable else VacsRunner(vacs_executable, base_args=vacs_base_args)

    stage_results: List[StageExecution] = []
    ath_dimension_rows = 0
    cleanup_results: List[Dict[str, Any]] = []
    versions_root = project_root / "versions"
    run_status = "succeeded"
    run_error_summary: Optional[str] = None

    try:
        for version_id in planning_summary.version_ids:
            version_started = time.perf_counter()
            version_payload = _read_json(_version_json_path(project_root, version_id))
            version_params = dict(version_payload.get("parameters", {}) or {})
            runner_mode = str(batch.runner_mode or project.constraints.runner_mode)

            cfg_path = _version_cfg_path(project_root, version_id)
            cfg_text = render_cfg_text(
                template_text=template_text,
                parameters=version_params,
                version_id=version_id,
                runner_mode=runner_mode,
            )
            cfg_path.parent.mkdir(parents=True, exist_ok=True)
            cfg_path.write_text(cfg_text, encoding="utf-8")

            if dry_run:
                elapsed = time.perf_counter() - version_started
                stage_results.append(
                    StageExecution(
                        version_id=version_id,
                        stage="dry_run",
                        status="ok",
                        exit_code=0,
                        timed_out=False,
                        summary_log="dry_run",
                    )
                )
                _update_version_state(
                    project_root,
                    version_id,
                    {
                        "status": "dry_run_completed",
                        "dry_run": True,
                        "run_id": effective_run_id,
                        "finished_at": _now_iso(),
                        "duration_seconds": elapsed,
                    },
                )
                writer.update_version_status(
                    version_id,
                    status="dry_run_completed",
                    run_id=effective_run_id,
                    duration_seconds=elapsed,
                    finished_at=_now_iso(),
                )
                cleanup_result = guarded_delete_tree(
                    _version_ath_work_path(project_root, version_id),
                    allowed_root=versions_root,
                    expected_dir_name="ath_work",
                    perform_delete=False,
                    deny_paths=(project_root, project_root.parent, versions_root),
                )
                cleanup_results.append(
                    {
                        "version_id": version_id,
                        "target": cleanup_result.target,
                        "deleted": cleanup_result.deleted,
                        "reason": cleanup_result.reason,
                    }
                )
                continue

            ath_stage_ok = ath_runner is None
            akabak_stage_ok = akabak_runner is None
            vacs_stage_ok = not vacs_required

            if ath_runner is not None:
                ath_work_dir = _version_ath_work_path(project_root, version_id)
                ath_work_dir.mkdir(parents=True, exist_ok=True)
                ath_result = ath_runner.run_cfg(
                    cfg_path,
                    version_logs_dir=_version_logs_dir(project_root, version_id),
                    workdir=ath_work_dir,
                )
                stage_results.append(_stage_from_result(version_id, "ath", ath_result))
                _update_version_state(
                    project_root,
                    version_id,
                    {
                        "status": "ath_ok" if ath_result.ok else "ath_failed",
                        "run_id": effective_run_id,
                        "ath_result": {
                            "exit_code": ath_result.exit_code,
                            "timed_out": ath_result.timed_out,
                            "stdout_log": ath_result.stdout_log,
                            "stderr_log": ath_result.stderr_log,
                            "summary_log": ath_result.summary_log,
                        },
                    },
                )
                writer.update_version_status(
                    version_id,
                    status="ath_ok" if ath_result.ok else "ath_failed",
                    run_id=effective_run_id,
                )
                ath_stage_ok = ath_result.ok

                ath_stdout = Path(ath_result.stdout_log).read_text(encoding="utf-8")
                dims = parse_ath_dimensions(ath_stdout)
                if dims.raw_line:
                    writer.write_ath_dimensions(
                        [
                            {
                                "project_id": project.project_id,
                                "batch_id": batch.batch_id,
                                "run_id": effective_run_id,
                                "version_id": version_id,
                                "horn_length_mm": dims.horn_length_mm,
                                "horn_width_mm": dims.horn_width_mm,
                                "horn_height_mm": dims.horn_height_mm,
                                "raw_line": dims.raw_line,
                                "source_file": ath_result.stdout_log,
                            }
                        ]
                    )
                    ath_dimension_rows += 1
                if not ath_result.ok and not continue_on_error:
                    elapsed = time.perf_counter() - version_started
                    writer.update_version_status(
                        version_id,
                        status="failed",
                        run_id=effective_run_id,
                        duration_seconds=elapsed,
                        finished_at=_now_iso(),
                        error_summary="ath_failed",
                    )
                    cleanup_results.append(
                        {
                            "version_id": version_id,
                            "target": str(_version_ath_work_path(project_root, version_id)),
                            "deleted": False,
                            "reason": "skipped_due_to_failure",
                        }
                    )
                    run_status = "failed"
                    continue

            if akabak_runner is not None:
                akabak_result = akabak_runner.run_project(
                    _version_abec_path(project_root, version_id),
                    version_logs_dir=_version_logs_dir(project_root, version_id),
                )
                stage_results.append(_stage_from_result(version_id, "akabak", akabak_result))
                _update_version_state(
                    project_root,
                    version_id,
                    {
                        "status": "akabak_ok" if akabak_result.ok else "akabak_failed",
                        "run_id": effective_run_id,
                        "akabak_result": {
                            "exit_code": akabak_result.exit_code,
                            "timed_out": akabak_result.timed_out,
                            "summary_log": akabak_result.summary_log,
                        },
                    },
                )
                writer.update_version_status(
                    version_id,
                    status="akabak_ok" if akabak_result.ok else "akabak_failed",
                    run_id=effective_run_id,
                )
                akabak_stage_ok = akabak_result.ok
                if not akabak_result.ok and not continue_on_error:
                    elapsed = time.perf_counter() - version_started
                    writer.update_version_status(
                        version_id,
                        status="failed",
                        run_id=effective_run_id,
                        duration_seconds=elapsed,
                        finished_at=_now_iso(),
                        error_summary="akabak_failed",
                    )
                    cleanup_results.append(
                        {
                            "version_id": version_id,
                            "target": str(_version_ath_work_path(project_root, version_id)),
                            "deleted": False,
                            "reason": "skipped_due_to_failure",
                        }
                    )
                    run_status = "failed"
                    continue

            if vacs_required and not vacs_executable:
                vacs_stage_ok = False
                summary_path = _version_logs_dir(project_root, version_id) / "vacs.export_pipeline.json"
                _write_json(
                    summary_path,
                    {
                        "error": "vacs_executable_missing",
                        "message": "VACS executable is required for configured export_specs.",
                        "remediation": "Configure vacs_exe in settings or remove export_specs for this batch.",
                    },
                )
                stage_results.append(
                    StageExecution(
                        version_id=version_id,
                        stage="vacs",
                        status="failed",
                        exit_code=1,
                        timed_out=False,
                        summary_log=str(summary_path),
                    )
                )
                _update_version_state(
                    project_root,
                    version_id,
                    {
                        "status": "vacs_failed",
                        "run_id": effective_run_id,
                        "vacs_result": {
                            "exit_code": 1,
                            "timed_out": False,
                            "summary_log": str(summary_path),
                            "error": "vacs_executable_missing",
                        },
                    },
                )
                writer.update_version_status(version_id, status="vacs_failed", run_id=effective_run_id)
                if not continue_on_error:
                    elapsed = time.perf_counter() - version_started
                    writer.update_version_status(
                        version_id,
                        status="failed",
                        run_id=effective_run_id,
                        duration_seconds=elapsed,
                        finished_at=_now_iso(),
                        error_summary="vacs_executable_missing",
                    )
                    cleanup_results.append(
                        {
                            "version_id": version_id,
                            "target": str(_version_ath_work_path(project_root, version_id)),
                            "deleted": False,
                            "reason": "skipped_due_to_failure",
                        }
                    )
                    run_status = "failed"
                    continue

            elif vacs_executable and export_specs:
                exports_dir = _version_exports_dir(project_root, version_id, effective_run_id)
                exports_dir.mkdir(parents=True, exist_ok=True)
                vacs_summary_path = _version_logs_dir(project_root, version_id) / "vacs.export_pipeline.json"
                try:
                    vacs_export_summary = run_vacs_export_specs(
                        executable=vacs_executable,
                        vacs_version=vacs_version,
                        project_id=project.project_id,
                        batch_id=batch.batch_id,
                        version_id=version_id,
                        abec_path=_version_abec_path(project_root, version_id),
                        export_specs=export_specs,
                        export_dir=exports_dir,
                        log_dir=_version_logs_dir(project_root, version_id),
                    )
                    _write_json(vacs_summary_path, vacs_export_summary)
                    stage_results.append(
                        StageExecution(
                            version_id=version_id,
                            stage="vacs",
                            status="ok",
                            exit_code=0,
                            timed_out=False,
                            summary_log=str(vacs_summary_path),
                        )
                    )
                    vacs_ingest = _ingest_vacs_exports(
                        writer=writer,
                        project=project,
                        batch=batch,
                        run_id=effective_run_id,
                        version_id=version_id,
                        exports_dir=exports_dir,
                    )
                    vacs_stage_ok = bool(vacs_export_summary.get("executed")) and not bool(vacs_ingest.get("parse_errors"))
                    if int(vacs_ingest.get("files_found", 0)) <= 0:
                        vacs_stage_ok = False
                    vacs_status = "vacs_ok" if vacs_stage_ok else "vacs_failed"
                    _update_version_state(
                        project_root,
                        version_id,
                        {
                            "status": vacs_status,
                            "run_id": effective_run_id,
                            "vacs_result": {
                                "exit_code": 0,
                                "timed_out": False,
                                "summary_log": str(vacs_summary_path),
                            },
                            "vacs_export_ingest": vacs_ingest,
                            "vacs_export_pipeline": vacs_export_summary,
                        },
                    )
                    writer.update_version_status(version_id, status=vacs_status, run_id=effective_run_id)
                except (VacsExportPipelineError, Exception) as exc:
                    vacs_stage_ok = False
                    _write_json(vacs_summary_path, {"error": str(exc), "vacs_version": vacs_version})
                    stage_results.append(
                        StageExecution(
                            version_id=version_id,
                            stage="vacs",
                            status="failed",
                            exit_code=1,
                            timed_out=False,
                            summary_log=str(vacs_summary_path),
                        )
                    )
                    _update_version_state(
                        project_root,
                        version_id,
                        {
                            "status": "vacs_failed",
                            "run_id": effective_run_id,
                            "vacs_result": {
                                "exit_code": 1,
                                "timed_out": False,
                                "summary_log": str(vacs_summary_path),
                                "error": str(exc),
                            },
                        },
                    )
                    writer.update_version_status(
                        version_id,
                        status="vacs_failed",
                        run_id=effective_run_id,
                        error_summary=str(exc),
                    )
                    if not continue_on_error:
                        elapsed = time.perf_counter() - version_started
                        writer.update_version_status(
                            version_id,
                            status="failed",
                            run_id=effective_run_id,
                            duration_seconds=elapsed,
                            finished_at=_now_iso(),
                            error_summary="vacs_export_failed",
                        )
                        cleanup_results.append(
                            {
                                "version_id": version_id,
                                "target": str(_version_ath_work_path(project_root, version_id)),
                                "deleted": False,
                                "reason": "skipped_due_to_failure",
                            }
                        )
                        run_status = "failed"
                        continue

            elif vacs_runner is not None:
                exports_dir = _version_exports_dir(project_root, version_id, effective_run_id)
                exports_dir.mkdir(parents=True, exist_ok=True)
                vacs_result = vacs_runner.run_export(
                    _version_abec_path(project_root, version_id),
                    version_logs_dir=_version_logs_dir(project_root, version_id),
                    workdir=exports_dir,
                )
                stage_results.append(_stage_from_result(version_id, "vacs", vacs_result))
                vacs_stage_ok = vacs_result.ok
                vacs_ingest: Dict[str, Any] = {}
                if vacs_result.ok:
                    vacs_ingest = _ingest_vacs_exports(
                        writer=writer,
                        project=project,
                        batch=batch,
                        run_id=effective_run_id,
                        version_id=version_id,
                        exports_dir=exports_dir,
                    )
                    if int(vacs_ingest.get("files_found", 0)) <= 0 or vacs_ingest.get("parse_errors"):
                        vacs_stage_ok = False
                vacs_status = "vacs_ok" if vacs_stage_ok else "vacs_failed"
                _update_version_state(
                    project_root,
                    version_id,
                    {
                        "status": vacs_status,
                        "run_id": effective_run_id,
                        "vacs_result": {
                            "exit_code": vacs_result.exit_code,
                            "timed_out": vacs_result.timed_out,
                            "summary_log": vacs_result.summary_log,
                        },
                        "vacs_export_ingest": vacs_ingest,
                    },
                )
                writer.update_version_status(version_id, status=vacs_status, run_id=effective_run_id)

            elapsed = time.perf_counter() - version_started
            final_ok = ath_stage_ok and akabak_stage_ok and vacs_stage_ok
            final_status = "success" if final_ok else "failed"
            _update_version_state(
                project_root,
                version_id,
                {
                    "status": final_status,
                    "run_id": effective_run_id,
                    "finished_at": _now_iso(),
                    "duration_seconds": elapsed,
                },
            )
            writer.update_version_status(
                version_id,
                status=final_status,
                run_id=effective_run_id,
                duration_seconds=elapsed,
                finished_at=_now_iso(),
                error_summary=None if final_ok else "version_stage_failed",
            )

            if final_ok:
                cleanup_result = guarded_delete_tree(
                    _version_ath_work_path(project_root, version_id),
                    allowed_root=versions_root,
                    expected_dir_name="ath_work",
                    deny_paths=(project_root, project_root.parent, versions_root),
                )
                cleanup_results.append(
                    {
                        "version_id": version_id,
                        "target": cleanup_result.target,
                        "deleted": cleanup_result.deleted,
                        "reason": cleanup_result.reason,
                    }
                )
            else:
                cleanup_results.append(
                    {
                        "version_id": version_id,
                        "target": str(_version_ath_work_path(project_root, version_id)),
                        "deleted": False,
                        "reason": "skipped_due_to_failure",
                    }
                )
                run_status = "failed"
    except Exception as exc:
        run_status = "failed"
        run_error_summary = str(exc)
        raise
    finally:
        writer.update_run(
            effective_run_id,
            status=run_status,
            finished_at=_now_iso(),
            error_summary=run_error_summary,
        )

    return RuntimeSummary(
        run_id=effective_run_id,
        run_status=run_status,
        project_id=project.project_id,
        batch_id=batch.batch_id,
        project_root=str(project_root),
        versions=list(planning_summary.version_ids),
        stage_results=stage_results,
        ath_dimension_rows=ath_dimension_rows,
        cleanup_results=cleanup_results,
        dry_run=dry_run,
    )
